### ISSUE TITLE
Modularizing similar to  apollograph  docs

### ISSUE THREAD

**Issue by tomalex0** [tomyitav/graphql-server-seed#2]
Thanks a lot for the seed, it helped me to understand modularizing.

Just want  to know if you explored the  modularizing as found in the docs. 

https://www.apollographql.com/docs/graphql-tools/generate-schema.html#modularizing

**Comment by tomyitav** [comment]
Hi @tomalex0, thanks for the compliments! :)
I find merge-graphql-schemas library way of merging types and resolvers more convenient. There is no need to even import all exported resolvers in one file and merge them - the directory structure allows you to automatically concat schemas :)
